let quote = document.querySelector('.quote');
let person = document.querySelector('.person');
let button = document.querySelector('.btn');

let quotes = [{
    quote: "Alone we can do so little; together we can do so much." , 
    person: "Helen Keller"},  {
    quote: "Because the people who are crazy enough to think they can change the world are the ones who do.",
    person: "Steve Jobs"},  {
    quote: "What is the essence of life? To serve others and to do good.", 
    person: "Aristotle"}, {
    quote: "Doing nothing for others is the undoing of ourselves.", 
    person: "Horace Mann"}, {
    quote: "Volunteering is an act of heroism on a grand scale. And it matters profoundly. It does more than help people beat the odds; it changes the odds.", 
    person: "Bill Clinton"}, {
    quote: "We make a living by what we get. We make a life by what we give.", 
    person: 'Winston Churchill'}, {
    quote:"Volunteerism is the voice of the people put into action. These actions shape and mold the present into a future of which we can all be proud.",
    person: "Helen Dyer"}, {
    quote: "Too often we underestimate the power of a touch, a smile, a kind word, a listening ear, an honest compliment, or the smallest act of caring, all of which have the potential to turn a life around.",
    person: "Leo Buscaglia"}, {
    quote: "Volunteers are the only human beings on the face of the earth who reflect this nation’s compassion, unselfish caring, patience, and just plain loving one another.",
    person:  "Erma Bombeck"}, {
    quote: "If our hopes of building a better and safer world are to become more than wishful thinking, we will need the engagement of volunteers more than ever.",
    person: "Kofi Annan"}, {
    quote: "Our generation has the ability and the responsibility to make our ever-more connected world a more hopeful, stable and peaceful place.",
    person: "Natalie Portman"}, {
    quote: "There is no better exercise for your heart than reaching down and helping to lift someone up.", 
    person: 'Bernard Meltzer'}, {
    quote: "As you grow older, you will discover that you have two hands — one for helping yourself, the other for helping others.", 
    person: "Audrey Hepburn"}, {
    quote: "Volunteers do not necessarily have the time; they have the heart.", 
    person: "Elizabeth Andrew"},{
    quote: "Volunteering is at the very core of being a human. No one has made it through life without someone else’s help.", 
    person: "Heather French Henry"}, {
    quote: "The smallest act of kindness is worth more than the grandest intention.", 
    person: "Oscar Wilde"},  {
    quote: "We cannot live only for ourselves. A thousand fibers connect us with our fellow men.", 
    person: "Herman Melville"}, {
    quote: "Start where you are. Use what you have. Do what you can.", 
    person: "Arthur Ashe"}, {
    quote: "The unselfish effort to bring cheer to others will be the beginning of a happier life for ourselves.", 
    person: "Helen Keller"}, {
    quote: "Every person can make a difference, and every person should try.", 
    person: "John F. Kennedy"},{ 
    quote: "Good actions give strength to ourselves and inspire good actions in others.", 
    person: "Plato"}, {
    quote: "Life’s most persistent and urgent question is, what are you doing for others?", 
    person: "Martin Luther King, Jr."}, {
    quote: "An effort made for the happiness of others lifts us above ourselves.", 
    person: "Lydia Maria Child"}, {
    quote: "Everybody can be great, because anybody can serve. You don’t have to have a college degree or make your subject and your verb agree or know the second theory of thermodynamics in physics to serve. You only need a heart full of grace. A soul generated by love.",    
    person: "Martin Luther King, Jr."}, {
    quote:  "Only by giving are you able to receive more than you already have.",
    person: "Jim Rohn"}, {
    quote: "You give but little when you give of your possessions. It is when you give of yourself that you truly give.", 
    person: "Kahlil Gibran"}, {
    quote: "You may not have saved a lot of money in your life, but if you have saved a lot of heartaches for other folks, you are a pretty rich man.", 
    person: "Seth Parker"}, {
    quote: "I urge young people to consider public service, whether they do it now by volunteering in their community or prepare for public service as an adult.",
    person: "John Walters"}, {
    quote: "Service to others is the rent you pay for your room here on earth.", 
    person: "Muhammad Ali"}, {
    quote: "The quality of your life will be determined by the quality of your contribution. When you work to improve the lives of others, your life improves automatically.",
    person: "Kurek Ashley"}, {
    quote: "Unless someone like you cares a whole awful lot, nothing is going to get better. It’s not.",
    person: "Dr. Seuss"}, {
    quote: "I am only one but still I am one. I cannot do everything, but still I can do something.", 
    person: "Edward Everett"}, {
    quote: "Help one another. There’s no time like the present, and no present like the time.",
    person:  "James Durst"},  {
    quote: "The best way to find yourself is to lose yourself in the service of others.",
    person: "Gandhi"}, {
    quote: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it’s the only thing that ever has.",
    person: "Margaret Mead"}, {
    quote: "Volunteers don’t get paid, not because they’re worthless, but because they’re priceless.",
    person: "Sherry Anderson"
    }]

button.addEventListener('click', () => {
    let random = Math.floor((Math.random() * quotes.length) + 1); //generates random quotes from index 0 to last quote in the array
    quote.innerText = quotes[random].quote; 
    person.innerText = quotes[random].person; 
})

